{% set name = "Automat" %}
{% set version = "0.7.0" %}
{% set sha256 = "cbd78b83fa2d81fe2a4d23d258e1661dd7493c9a50ee2f1a5b2cac61c1793b0e" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}
  patches:
    - 0001-m2r-is-not-a-strict-build-dependency.patch

build:
  number: 0
  entry_points:
    - automat-visualize = automat._visualize:tool
  script: python setup.py install --single-version-externally-managed --record record.txt

requirements:
  host:
    - python
    - setuptools
    - setuptools_scm
  run:
    - python
    - attrs
    - six

test:
  imports:
    - automat

about:
  home: https://github.com/glyph/Automat
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: 'self-service finite-state machines for the programmer on the go'
  description: |
    Automat is a library for concise, idiomatic Python expression of
    finite-state automata (particularly deterministic finite-state
    transducers).
  doc_url: http://automat.readthedocs.io
  dev_url: https://github.com/glyph/automat

extra:
  recipe-maintainers:
    - CJ-Wright
    - nehaljwani
