travis:
  secure:
    BINSTAR_TOKEN: aBlSxfvosPiGguvREBJg4IeAL6s6snrtyhMTEvT7XmeSjES/3V2oEURF+bpmiXv7UX6UkryoIMrWCSSqPgBfqHtqalwmzpPRRF9YzjFY56OugX/UTTq8LMOrWs8pbIDrtn8a3Cg64sWa0lLcBsKSjHLXeSgW3/sphCJmz6dNwNTOVWGWWXxtmXrQ25kD31WFwnB/zw/bPecAsIqjVWpwomsHErQgPZyZjjuwwke6NQuZG5k6kg/ao1BHp5D7uhlpIzu5zIALxYoYqJsW2NPuFO2Z79Xhs5Dc4upf73iGoam+cadYhfI7/K6397snZbtrPJbOFsml0FNaKrBkOaU3dtnENd22MdbV3o+LfQqnpEOCUngF2t+NVByZ3ZBV79l5U06UmQreIOnPrZeYKD31a1+rtsYYUJr86mIksyd6PqDpmDD5OmICE9h4Frpm21jZp1UvK1W9sZhiODBnUFFxdmEf0wBltxR2J761IXQzc/ML7gKLdRh+h8cJhtWXkXh6YOnQTEew6B+ThiGxIMNyy0n9osrGeYdM0cssvuvjI1jH9Ly/zg/mZLtSAo1Cr4hONHZMXcvxtOk7wBvP6BOCAG3iPmKjESSrguZDPQy1d0MA8vyA4j9OQiPm5NfeX7Vcid9AOZAah0QmWF6ADfM3xc5+UdDHfoXEsgFlsV6f944=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
